baseURL = "https://nubedeideas.net"
title = "Nube de Ideas"
author = "ndi"
languageCode = "es"
DefaultContentLanguage = "es"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Nube de Ideas Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Nube de Ideas"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Prensa y Relaciones Públicas"
    meta_og_title = "Nube de Ideas"
    meta_og_type = "website"
    meta_og_url = "https://nubedeideas.net"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "quienessomos"
    name = "Quienes Somos"
    url = "/quienessomos/"
    weight = 1

  [[menu.main]]
    identifier = "quehacemos"
    name = "Que Hacemos"
    url = "/quehacemos/"
    weight = 2

  [[menu.main]]
    identifier = "nuestrosartistas"
    name = "Nuestros Artistas"
    url = "/artistas/"
    weight = 3

  [[menu.main]]
    identifier = "portafolio"
    name = "Portafolio"
    url = "/portafolio/"
    weight = 4

  [[menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/blog/"
      weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/nubedeideas_oficial/"
    pre = "<i class='fa-brands fa-instagram text-2xl'></i>"
      weight = 2

